### ISSUE TITLE
New release is needed

### ISSUE THREAD

**Issue by vvv** [ehamberg/typeclassopedia-md#1]
The Typeclassopedia had been [updated in June 2017](https://byorgey.wordpress.com/2017/06/07/the-typeclassopedia-is-now-up-to-date/), yet the most recent [EPUB release](https://github.com/ehamberg/typeclassopedia-md/releases) is of December 2014.

**Comment by ehamberg** [comment]
Yes, absolutely! Would be happy for any help with this. Given the substantial changes the Wiki version has gone through, I think a new Wiki → Markdown conversion should be done.

**Comment by vvv** [comment]
[pandoc](http://pandoc.org/) does all the conversion necessary.
```
pandoc --toc -s -S -f mediawiki -t epub -o typeclassopedia.epub typeclassopedia.mediawiki
```
Note that you have to download [Typeclassopedia-diagram.png](https://wiki.haskell.org/wikiupload/d/df/Typeclassopedia-diagram.png) first.

**Comment by ehamberg** [comment]
Unfortunately it's not that easy (but it can help a lot!):

- The notes are lost
- The wiki links don't work
- There are some markup errors in the epub file

I don't really see a way of doing a fully automatic conversion (but I would love to be proved wrong!). :)

**Comment by ehamberg** [comment]
Just pushed a new, complete conversion and uploaded a [pre-release (PDF + ePub)](https://github.com/ehamberg/typeclassopedia-md/releases/tag/2017-08-04-pre). Would really appreciate feedback on mistakes or wrong formatting. :)

**Comment by srid** [comment]
@ehamberg Margins in the PDF are too big. Not very suitable for printing IMO. I guess I could play with the PDF generation myself ...

**Comment by ehamberg** [comment]
@srid You certainly could. I'm quite sure the PDF uses the default margin size for LaTeX documents, which I personally find easy to read. (Though that could certainly be because it's what I'm used to. :)

**Comment by srid** [comment]
This worked for me:

```diff
--- a/typeclassopedia.md
+++ b/typeclassopedia.md
@@ -1,5 +1,8 @@
-% Typeclassopedia
-% Brent Yorgey
+---
+title:  Typeclassopedia
+author: Brent Yorgey
+geometry: margin=3cm
+---
 
 Originally published 12 March 2009 in [issue 13](http://www.haskell.org/wikiupload/8/85/TMR-Issue13.pdf) of [the Monad.Reader](http://themonadreader.wordpress.com/). Ported to the Haskell wiki in November 2011 by Geheimdienst. Converted to Markdown in August 2013 by Erlend Hamberg. Converted to EPUB format with [pandoc](http://www.pandoc.org).
 ```
